spring.application.name=backend

app.git.repositories-directory=./data/repositories

github.username=${GITHUB_USERNAME:oauth2}
github.token=${GITHUB_TOKEN:}
github.webhook-secret=${GITHUB_WEBHOOK_SECRET:}